### ISSUE TITLE
Drupal Console RC5 doesn't work on multisite configuration when sites/default is not used

### ISSUE THREAD

**Issue by bpresles** [hechoendrupal/DrupalConsole#2783]
Hello,

I've noticed that when used on mutlisite configuration without site installed on sites/default, Drupal Console RC5 doesn't work at all.

Indeed, even the "drupal multisite:debug" command doesn't work and report that Drupal is not installed, while on Beta 5 (last previous I used) it was working just fine.

Also even if I use the sites/default and install a Drupal on it, when I use "drupal list --uri=<other_site_uri>" on a non installed site, it does list all the commands even though the site specified is not installed. In that case it should report that Drupal should be installed first for the specified multisite site.

**Comment by mickaelperrin** [comment]
Can confirm the issue, and related to #2002.

It looks like the support for `uri` has been dropped ? Can someone confirm this ?

**Comment by mickaelperrin** [comment]
@bpresles just submitted a PR that should resolve the issue. #2850

**Comment by PatrickBauer** [comment]
@mickaelperrin Your PR works for the --uri, but the multisite:debug command still doesn't work.

**Comment by Sutharsan** [comment]
This issue was confimed three days ago during a long debug session with @jmolivas in the (current) RC25 release. Without a sites/default/settings.php a single and a multi-site will not work. A complete sites/sites.php is present in both cases.
